# action.yml
name: "CI"
description: "Runs unit and integration tests"

on: [push]

runs:
  using: 'docker'
  image: 'Dockerfile'

jobs:
  test:
    steps:
      - name: Run the tests
        run: coverage run tests/runner.py && coverage html --omit=*/venv/*,*/usr/*,*/lib/*,*/tests/* -i